content:
  - name: blog
  - label: Blog
  - path: src/content/blog
  - type: collection
  - fields: [title, description, date, tags, cover]

media:
  - input: public/covers
  - output: /public/covers
  
  